project_name: summa
project_directory: [dev,prod,staging]
project_file: [compose.yaml,deploy.sh]


# Env for selfhostedrunner.yml
runner_for: [api,web,backend] # how many runner you want to setup
repositories:
  {{repo_name}}:
    github_link: "{{your repo link}}"
    action_token: "{{your action token }}"

  {{repo_name}}:
    github_link: "{{your repo link}}"
    action_token: "{{your action token}}"


# two directory will be created with the respective {{repo_name}}, if you want to add more repo than just add another key:value pair.
# inside the directory created for the repo three directory dev, prod, staging will be created . 
# If you want to add more environments than simply add the environment name to the list .
# inside the environment directory a compose.yaml and deploy.sh file will be created with the respective environment variables.

