- hosts: ec2-instance
  gather_facts: true
  
  vars_files:
    - env.yml

   
  tasks:
    - import_tasks: tasks/Update.yml
    - import_tasks: tasks/runnerversion.yml
    - import_tasks: tasks/selfhostedrunner.yml
