- hosts: ec2-instance  # Define the target hosts group for this playbook
  gather_facts: true


  vars_files:
    - env.yml


  tasks:
    - import_tasks: tasks/copy-dir.yml
    - import_tasks: tasks/template.yml
    - import_tasks: tasks/selfhostedrunner.yml
    # - import_tasks: tasks/Update.yml
