# Directory setup for project

- name: Ensure destination directory '~/project_name' exists
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/{{ project_name }}"
    state: directory
    mode:  '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true


- name: Ensure dev directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ project_name }}/dev"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Ensure prod directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ project_name }}/prod"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Ensure staging directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ project_name }}/staging"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true


- name: Copy dev configuration
  ansible.builtin.copy:
    src: 'files/project_name/dev/'
    dest: '{{  ansible_user_dir }}/{{ project_name }}/dev'  
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Copy prod configuration
  ansible.builtin.copy:
    src: 'files/project_name/prod/'
    dest: '{{  ansible_user_dir }}/{{ project_name }}/prod'  
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Copy staging configuration
  ansible.builtin.copy:
    src: 'files/project_name/staging/'
    dest: '{{  ansible_user_dir }}/{{ project_name }}/staging'  
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

# Directory setup for operations
- name: Ensure destination directory '~/ops/traefik' exists
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/ops/traefik"
    state: directory
    mode:  '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true




