# Directory setup for project
- name: Ensure destination directory '~/project_name' exists
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/{{ project_name }}"
    state: directory
    mode:  '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Ensure all environment directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ project_name }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
  loop: "{{ project_directory }}"

- name: Ensure standard directory storage exists in {{ ansible_user_dir }}/{{ project_name }}/{{ item }}
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ project_name }}/{{ item }}/storage"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
  loop: "{{ project_directory }}"

- name: Ensure compose.yaml and deploy.sh exists in each environment's directory
  ansible.builtin.file: 
    path: "{{ ansible_user_dir }}/{{ project_name }}/{{ item.0 }}/{{ item.1 }}"
    state: touch
    mode: "{{ '0775' if item.1.endswith('.sh') else '0664' }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
  loop: "{{ project_directory | product(project_file) }}"


# Directory setup for operations
- name: Ensure destination directory '~/ops/traefik' exists
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/ops/traefik"
    state: directory
    mode:  '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Ensure config directory exists within '~/ops/traefik'
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/ops/traefik/config"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true






