
- name: Ensure /opt/action-runner directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ops/action-runner-{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ runner_for }}"
  become: true

- name: Download the latest runner package in ~/ops directory
  ansible.builtin.get_url:
    url: https://github.com/actio.0ns/runner/releases/download/v2.316.1/actions-runner-linux-x64-2.316.1.tar.gz
    dest: "{{ ansible_user_dir }}/ops/actions-runner-linux-x64-2.316.1.tar.gz"
    mode: '0644'
  become: true





- name: Set owner and group for the downloaded file
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ops/actions-runner-linux-x64-2.316.1.tar.gz"
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  become: true

- name: Extract the runner package in each directory 
  ansible.builtin.command: 
    cmd: "sudo tar xzf {{ ansible_user_dir }}/ops/actions-runner-linux-x64-2.316.1.tar.gz -C {{ ansible_user_dir }}/ops/action-runner-{{ item }}"
  loop: "{{ runner_for }}"
  become: true

- name: Set owner and group for extracted files
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ops/action-runner-{{ item }}"
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: yes
  loop: "{{ runner_for }}"
  become: true


- name: Run configuration script
  ansible.builtin.command: 
    cmd: "{{ ansible_user_dir }}/ops/action-runner-{{ item }}/config.sh --unattended --url $github_link --token $action_token --name {{ item }}" 
  loop: "{{ runner_for }}"
  become: false
 
- name: Install SVC for all 
  ansible.builtin.command:
    cmd: "sudo ./svc.sh install"
    chdir: "{{ ansible_user_dir }}/ops/action-runner-{{ item }}"
  loop: "{{ runner_for }}"
  become: true


- name: Start SVC for all
  ansible.builtin.command: 
    cmd: "sudo ./svc.sh start"
    chdir: "{{ ansible_user_dir }}/ops/action-runner-{{ item }}"
  loop: "{{ runner_for }}"
  become: true

# - name: Start the runner
#   ansible.builtin.command: 
#     cmd: "{{ ansible_user_dir }}/ops/action-runner-{{ item }}/run.sh"
#   loop: "{{ runner_for }}"
