- name: Deploy project template for compose file and bash script templates
  template:
    src: ../templates/{{ item }}.j2
    dest: "{{ ansible_user_dir }}/{{ project_name }}/{{ APP_ENVIRONMENT }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ '0775' if item.endswith('.sh') else '0664' }}"
  become: true
  loop:
    - compose.yaml
    - deploy.sh


- name: Set Traefik compose and up.sh
  template:
    src: ../templates/{{ item }}.j2
    dest: "{{ ansible_user_dir }}/ops/traefik/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ '0775' if item.endswith('.sh') else '0664' }}"
  become: true
  loop:
    - traefik-compose.yaml
    - up.sh

- name: Set Traefik config
  template:
    src: ../templates/{{ item }}.j2
    dest: "{{ ansible_user_dir }}/ops/traefik/config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ '0775' if item.endswith('.sh') else '0664' }}"
  become: true
  loop:
    - traefik_config.yaml

  
- name: Print the environment
  debug:
    msg: "The application environment is set to {{ APP_ENVIRONMENT }}"
- name: Print server port
  debug:
    msg: "The server port is set to {{ SERVER_PORT }}"
- name: Print API link
  debug:
    msg: "The API link is set to {{ API_LINK }}"
- name: Print network
  debug:
    msg: "The network is set to {{ NETWORK }}"
    
