- name: Deploy project template for compose file and bash script templates
  template:
    src: ../templates/{{ item }}.j2
    dest: "{{ ansible_user_dir }}/{{ project_name }}/{{ APP_ENVIRONMENT }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0666
  become: true
  loop:
    - compose.yaml
    - deploy.sh

- name: Set executable permissions on deploy.sh
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ project_name }}/{{ APP_ENVIRONMENT }}/deploy.sh"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true


- name: Deploy Traefik templates
  template:
    src: ../templates/{{ item }}.j2
    dest: "{{ ansible_user_dir }}/ops/traefik/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0666
  become: true
  loop:
    - traefik-compose.yaml
    - traefik.yaml
    - up.sh

- name: Set executable permissions on up.sh
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/ops/traefik/up.sh"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

  
- name: Print the environment
  debug:
    msg: "The application environment is set to {{ APP_ENVIRONMENT }}"
- name: Print server port
  debug:
    msg: "The server port is set to {{ SERVER_PORT }}"
- name: Print API link
  debug:
    msg: "The API link is set to {{ API_LINK }}"
- name: Print network
  debug:
    msg: "The network is set to {{ NETWORK }}"
    
